---
kind: pipeline
name: build
steps:
  - name: pr/docker
    image: plugins/docker:17.12
    settings:
      repo: &docker_repo quay.io/suzuki_shunsuke/test-quayio-drone
      registry: quay.io
      dry_run: true
      username:
        from_secret: quayio_username
      password:
        from_secret: quayio_password
    when:
      event:
        - pull_request
  - name: push/docker
    image: plugins/docker:17.12
    settings:
      repo: *docker_repo
      registry: quay.io
      dry_run: true
      username:
        from_secret: quayio_username
      password:
        from_secret: quayio_password
    when:
      event:
        - push
