---
pipeline:
  tag/docker:
    image: plugins/docker:17.12
    settings:
      tags:
        - latest
        - "${DRONE_TAG##v}"
      repo: quay.io/repository/suzuki_shunsuke/test-quayio-drone
      username:
        from_secret: quayio_username
      password:
        from_secret: quayio_password
    when:
      event: tag
      ref: refs/tags/*
  push/docker:
    image: plugins/docker:17.12
    settings:
      tags: latest
      repo: quay.io/repository/suzuki_shunsuke/test-quayio-drone
      username:
        from_secret: quayio_username
      password:
        from_secret: quayio_password
    when:
      event: push
  pr/docker:
    image: plugins/docker:17.12
    settings:
      repo: quay.io/repository/suzuki_shunsuke/test-quayio-drone
      dry_run: true
    when:
      event: pull_request
